language: python
python:
  - "2.7"
  - "3.3"
  - "pypy"
script:
  - "nosetests --verbose"
  - "flake8 --show-source flask_bugzscout test"
notifications:
  email: thomas.vandoren@gmail.com
matrix:
  allow_failures:
    - python: "3.3"
